var agora = new Date() // var puxa o horário atual;
var hora = agora.getHours() // essa var puxa a hora atual gerada na var acima;
console.log(`Agora são ${hora} horas.`) // essa var printa a hora atual;
if (hora >= 0 && hora < 6) {       // se a hora for maior que 00h e menor que 6h...
    console.log('BOA MADRUGADA')
} else if (hora <= 12) {           // se a hora for menor ou igual a 12h...
    console.log('BOM DIA')
} else if (hora <= 18) {           //  se a hora for menor ou igual às 18h...
    console.log('BOA TARDE')
} else if (hora > 18) {            // se a hora for maior que 18h...
    console.log('BOA NOITE')
}
